name: General issue
description: Open a general issue

body:
- type: markdown
  attributes:
    value: |
      Thank you for providing feedback on Python packaging!


- type: textarea
  id: problem
  attributes:
    label: Problem description
    description: |
      To help us help you, please be as detailed as possible.
      
  validations:
    required: true
